title: Hierarchical Invariant Learning for Domain Generalization Recommendation
description: This is the official release for HIRL.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

github:
  zip_url: https://github.com/anonymous-hirl/HIRL/tree/main/project
